import { HttpException, type HttpStatus } from '@nestjs/common';

export type AppErrorCode =
  | 'AUTH_EMAIL_ALREADY_REGISTERED'
  | 'AUTH_INVALID_CREDENTIALS'
  | 'AUTH_CURRENT_PASSWORD_INVALID'
  | 'AUTH_PASSWORD_POLICY_NOT_MET'
  | 'AUTH_PASSWORD_RESET_TOKEN_INVALID'
  | 'EMAIL_SMTP_NOT_READY'
  | 'AUTH_SESSION_EXPIRED'
  | 'AUTH_ADMIN_ACCESS_REQUIRED'
  | 'AUTH_PORTAL_ACCESS_REQUIRED'
  | 'AUTH_WORKSPACE_UNAVAILABLE'
  | 'CAPTION_CREATE_FAILED'
  | 'CAPTION_NOT_FOUND'
  | 'FILE_IN_USE_BY_PUBLISHING'
  | 'FILE_IN_USE_BY_WATERMARK'
  | 'CHANNEL_PROFILE_SYNC_COOLDOWN'
  | 'CHANNEL_PROFILE_SYNC_UNAVAILABLE'
  | 'CHANNEL_PROFILE_SYNC_UNSUPPORTED'
  | 'RSS_FEED_VALIDATION_RATE_LIMITED'
  | 'SUPPORT_CATEGORY_UNAVAILABLE'
  | 'SUPPORT_TICKET_NOT_FOUND'
  | 'SUPPORT_TICKET_NOT_OPEN'
  | 'WATERMARK_NOT_FOUND'
  | 'WATERMARK_TARGET_EXISTS'
  | 'TEAM_ACCESS_DENIED'
  | 'INVITATION_EMAIL_MISMATCH'
  | 'INVITATION_EXPIRED'
  | 'INVITATION_ALREADY_USED'
  | 'ROLE_CHANGE_NOT_ALLOWED'
  | 'ACCOUNT_GRANT_NOT_ALLOWED'
  | 'MEMBER_LIMIT_REACHED'
  | 'OAUTH_CALLBACK_INVALID'
  | 'OAUTH_PROVIDER_CONFIGURATION_INVALID'
  | 'OAUTH_PROVIDER_NOT_READY'
  | 'OAUTH_PROVIDER_UNSUPPORTED'
  | 'OAUTH_STATE_INVALID'
  | 'OAUTH_STATE_EXPIRED'
  | 'OAUTH_STATE_CONSUMED'
  | 'VALIDATION_FAILED'
  | 'INFRASTRUCTURE_UNAVAILABLE'
  | 'INTERNAL_SERVER_ERROR'
  | 'REQUEST_FAILED';

export class AppException extends HttpException {
  constructor(
    readonly code: AppErrorCode,
    status: HttpStatus,
  ) {
    super({ code }, status);
  }
}
